{% set version = "2.13.1" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: fontconfig
  version: {{ version }}

source:
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.bz2
  sha256: f655dd2a986d7aa97e052261b36aa67b0a64989496361eca8d604e6414006741
  patches:
    # This patch won't be submitted upstream. It's use here is to ensure the prefix used
    # to refer to the `fonts.conf` file.
    - fcf.patch       # [linux]
    # Windows patches from https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-fontconfig
    - 0001-fix-config-linking.all.patch  # [win]
    - 0002-fix-mkdir.mingw.patch         # [win]
    - 0003-fix-link-libintl.patch        # [win]
    - 0004-fix-mkdtemp.mingw.patch       # [win]
    - 0005-fix-setenv.mingw.patch        # [win]
    - 0007-pkgconfig.mingw.patch         # [win]
    # conda-forge/msys2 specifics
    - msys.patch           # [win]
    - windows-tests.patch  # [win]

build:
  number: 0
  binary_has_prefix_files:        # [unix]
    - lib/libfontconfig.so.1.*    # [linux]
    - lib/libfontconfig.*.dylib*  # [osx]
  run_exports:
    # remove symbols basically never (once, in 2006).
    #    https://abi-laboratory.pro/tracker/timeline/fontconfig/
    - {{ pin_subpackage('fontconfig') }}

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-gperf  # [win]
    - m2-libtool  # [win]
    - m2-patch  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-xz  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - make
    - gperf     # [not win]
    - gettext   # [not win]
    - libtool   # [not win]
    - automake  # [not win]
    - autoconf  # [not win]
  host:
    - m2w64-gettext  # [win]
    - freetype
    - icu  # [not win]
    - libpng
    - libxml2
    - libiconv  # [not linux and not win]
    - libuuid  # [linux]
  run:
    - m2w64-gettext  # [win]
    - freetype
    - icu  # [not win]
    - libpng
    - libxml2
    - libiconv  # [not linux and not win]
    - libuuid  # [linux]

test:
  commands:
    # Test CLI.
    - fc-cache --help
    - fc-cat --help
    - fc-list --help
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help

    # Test for libraries.
    {% set lib_idents = [ "fontconfig" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.a  # [not win]
    - test -f $PREFIX/lib/lib{{ lib_ident }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.a exit /b 1  # [win]
    {% endfor %}

about:
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: 'A library for configuring and customizing font access'
  description: |
    Fontconfig is a library designed to provide system-wide font configuration,
    customization and application access.
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  dev_url: https://cgit.freedesktop.org/fontconfig/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pkgw
