# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MBc1rFscGYor5T5S+lwSR//bsUBYyV/KKSz2Sjl4t37JDTbm7bcagC6eRBu6y6FjIcs2I50IA94Nl6PwgmwPQQR9QjTYs1ZkqqvW++o3gDgg/KDzuvuiiiW+18bKi129H1gPJj9XfqJo0hzsFQG6mSx/GtQK8I9dO8miR356Zx6QQZtB8excjzp/NPi94na6Ku6zq/B6EgIL5YNgewZcPe0eF5HyhWCwTF6Ue/9fpVWDjHtbD8SgiPG6K3cUJpPSWQK3bco/rtx4P7if6SqQ20pc/INOE/19Nh8QQ7wXL/qtggKGKTzGWmSdZYXZyQ9J1gSPHGh97FOsLok9z3ujeaU5hhQiy+b6O6rwnbEzGZ5XspfxzyyhsE7ksOCGlmVaYEOfY7FqOBnA0QpSLegGlojwNYm1lXynXFosWwD+G8qlLi0369AeJrn4YEL/VnMOPS9RYSRQBpgVWN+cOWvfMFISeIezWdAgxS3Vm7AC7QC87OxjzmeckoQWhB4FZJ+2A8G5+I5yEo1VRMTtfnAOJdgMofqy5VKbMVCHa6IsvatBNvd4iQq5llB3dILivgn0aUaL9AzpRtUul5TAAQdhPZncuh/W4eC1MARqZaSLfkam2H3QmoNa80RCHsWP0epqElm4uAx3xqAnuS5RQo8tCYgKaqI1IYVqkxMW/3RpFFI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
